In [3]:
import time

In [4]:
def log_formatter(msg):
    def log_message():
        time_str = time.strftime('%C', time.localtime(time.time()))
        print(time_str, end='')
        print('--->', end='')
        print(msg)
    
    return log_message

In [5]:
test_log_msg = log_formatter('test log')
runtime_log_msg = log_formatter('runtime log')

In [6]:
test_log_msg()
runtime_log_msg()

20--->test log
20--->runtime log


In [7]:
def log_decorator(param_func):
    def log_message():
        time_str = time.strftime('%C', time.localtime(time.time()))
        print(time_str, end='')
        print('--->', end='')
        return param_func()
    
    return log_message

In [8]:
def test_log_msg():
    print('This is test log message')

In [9]:
def runtime_log_msg():
    print('This is runntime log message')

In [10]:
test_log = log_decorator(test_log_msg)
runtime_log = log_decorator(runtime_log_msg)

In [11]:
test_log()

20--->This is test log message


In [12]:
runtime_log()

20--->This is runntime log message


In [13]:
def get_double(a):
    return a *2

In [14]:
def print_line():
    return 
    print('=' * 30)

In [15]:
print_line()

In [18]:
@log_decorator
def test_log_msg():
    print('this is test log message')

@log_decorator
def funtime_mo():
    print('This is runtime log')

In [19]:
import numpy as np

In [20]:
n = np.arange(1,7).reshape(2,3)
print(n)

[[1 2 3]
 [4 5 6]]


In [22]:
a = np.array([0,10,20,30,40,50])
print(a)

[ 0 10 20 30 40 50]


In [24]:
print(a[[1,3,4]])

[10 30 40]


In [25]:
b = np.arange(10,100,10).reshape(3,3)
print(b)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [26]:
print(b[0,2])

30


In [27]:
print(b[0,2],[0,1])

30 [0, 1]


In [29]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [30]:
print(a[a>3])

[4 5 6]


In [31]:
print(a[a%2 == 0])

[2 4 6]


In [33]:
a = np.array([0,10,20,30,40,50])
print(a)

[ 0 10 20 30 40 50]


In [34]:
print(a[1:4])

[10 20 30]


In [35]:
print(a[:3])

[ 0 10 20]


In [36]:
print(a[2:])

[20 30 40 50]


In [38]:
a = np.arange(10,100,10).reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [39]:
print(a[1:3,1:3])

[[50 60]
 [80 90]]


In [41]:
print(a[:3,1:])

[[20 30]
 [50 60]
 [80 90]]


In [42]:
print(a[1][0:2])

[40 50]


In [45]:
print(a[1:2],[0,2])

[[40 50 60]] [0, 2]


In [46]:
import pandas as pd

In [47]:
sl = pd.Series([10,20,30,40,50])
print(sl)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [48]:
print(sl.index)

RangeIndex(start=0, stop=5, step=1)


In [49]:
print(sl.values)

[10 20 30 40 50]


In [50]:
print(type(sl.values))

<class 'numpy.ndarray'>


In [51]:
s2 = pd.Series(['a','b','c',1,2,3])
print(s2)

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object


In [53]:
s3 = pd.Series([np.nan, 1,2])#nan(Not A Number)
print(s3)

0    NaN
1    1.0
2    2.0
dtype: float64


In [56]:
index_data = ['2021-03-20','2021-03-21','2021-03-22','2021-03-23']
s4 = pd.Series([200,187,np.nan,210], index=index_data)
print(s4)

2021-03-20    200.0
2021-03-21    187.0
2021-03-22      NaN
2021-03-23    210.0
dtype: float64


In [58]:
s5 = pd.Series({'국어':100, '영어':95, '수학':100})
print(s5)

국어    100
영어     95
수학    100
dtype: int64


In [60]:
p = pd.date_range(start='2021-08-01',end='2021-08-31')
print(p)

DatetimeIndex(['2021-08-01', '2021-08-02', '2021-08-03', '2021-08-04',
               '2021-08-05', '2021-08-06', '2021-08-07', '2021-08-08',
               '2021-08-09', '2021-08-10', '2021-08-11', '2021-08-12',
               '2021-08-13', '2021-08-14', '2021-08-15', '2021-08-16',
               '2021-08-17', '2021-08-18', '2021-08-19', '2021-08-20',
               '2021-08-21', '2021-08-22', '2021-08-23', '2021-08-24',
               '2021-08-25', '2021-08-26', '2021-08-27', '2021-08-28',
               '2021-08-29', '2021-08-30', '2021-08-31'],
              dtype='datetime64[ns]', freq='D')


In [63]:
p = pd.date_range(start='2021/08/01',end='2021.08.31')
print(p)

DatetimeIndex(['2021-08-01', '2021-08-02', '2021-08-03', '2021-08-04',
               '2021-08-05', '2021-08-06', '2021-08-07', '2021-08-08',
               '2021-08-09', '2021-08-10', '2021-08-11', '2021-08-12',
               '2021-08-13', '2021-08-14', '2021-08-15', '2021-08-16',
               '2021-08-17', '2021-08-18', '2021-08-19', '2021-08-20',
               '2021-08-21', '2021-08-22', '2021-08-23', '2021-08-24',
               '2021-08-25', '2021-08-26', '2021-08-27', '2021-08-28',
               '2021-08-29', '2021-08-30', '2021-08-31'],
              dtype='datetime64[ns]', freq='D')


In [64]:
p = pd.date_range(start='2021-08-10',periods=7)
print(p)

DatetimeIndex(['2021-08-10', '2021-08-11', '2021-08-12', '2021-08-13',
               '2021-08-14', '2021-08-15', '2021-08-16'],
              dtype='datetime64[ns]', freq='D')


In [66]:
p = pd.date_range(start='2021-08-01',periods=4, freq='2D')
print(p)

DatetimeIndex(['2021-08-01', '2021-08-03', '2021-08-05', '2021-08-07'], dtype='datetime64[ns]', freq='2D')


In [68]:
p =pd.date_range(start='2021-08-18',periods = 5, freq = 'w')
print(p)

DatetimeIndex(['2021-08-22', '2021-08-29', '2021-09-05', '2021-09-12',
               '2021-09-19'],
              dtype='datetime64[ns]', freq='W-SUN')


In [69]:
p = pd.date_range(start='2021-07-23',periods=12, freq='2BM')
print(p)

DatetimeIndex(['2021-07-30', '2021-09-30', '2021-11-30', '2022-01-31',
               '2022-03-31', '2022-05-31', '2022-07-29', '2022-09-30',
               '2022-11-30', '2023-01-31', '2023-03-31', '2023-05-31'],
              dtype='datetime64[ns]', freq='2BM')


In [71]:
p = pd.date_range(start='2021-01-04', periods=4, freq='QS')
print(p)

DatetimeIndex(['2021-04-01', '2021-07-01', '2021-10-01', '2022-01-01'], dtype='datetime64[ns]', freq='QS-JAN')


In [72]:
p =pd.date_range(start='2021-02-01', periods=3, freq='AS')
print(p)

DatetimeIndex(['2022-01-01', '2023-01-01', '2024-01-01'], dtype='datetime64[ns]', freq='AS-JAN')


In [74]:
p = pd.date_range(start='2021-01-01 08:00', periods=10, freq='H')
print(p)

DatetimeIndex(['2021-01-01 08:00:00', '2021-01-01 09:00:00',
               '2021-01-01 10:00:00', '2021-01-01 11:00:00',
               '2021-01-01 12:00:00', '2021-01-01 13:00:00',
               '2021-01-01 14:00:00', '2021-01-01 15:00:00',
               '2021-01-01 16:00:00', '2021-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='H')


In [75]:
cbh = pd.offsets.CustomBusinessHour(start='09:00',end = '18:00',weekmask = 'Mon Tue Wed Thu Fri')
print(cbh)

<CustomBusinessHour: CBH=09:00-18:00>


In [76]:
p2 = pd.date_range(start='2021-01-01 08:00', periods=10, freq=cbh)
print(p2)

DatetimeIndex(['2021-01-01 09:00:00', '2021-01-01 10:00:00',
               '2021-01-01 11:00:00', '2021-01-01 12:00:00',
               '2021-01-01 13:00:00', '2021-01-01 14:00:00',
               '2021-01-01 15:00:00', '2021-01-01 16:00:00',
               '2021-01-01 17:00:00', '2021-01-04 09:00:00'],
              dtype='datetime64[ns]', freq='CBH')


In [79]:
p = pd.date_range(start='2021-01-01',periods=4, freq='10S')
print(p)

DatetimeIndex(['2021-01-01 00:00:00', '2021-01-01 00:00:10',
               '2021-01-01 00:00:20', '2021-01-01 00:00:30'],
              dtype='datetime64[ns]', freq='10S')


In [88]:
index_date = pd.date_range(start='2021-08-01', periods=5, freq='D')
p = pd.Series([51,63,59,48,60],index= index_date)
print(p)

2021-08-01    51
2021-08-02    63
2021-08-03    59
2021-08-04    48
2021-08-05    60
Freq: D, dtype: int64


In [89]:
df = pd.DataFrame([[1,2,3,],[4,5,6],[7,8,9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [90]:
data_list = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(data_list)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [104]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index_date = pd.date_range('2021-08-01',periods=4)
columns_list = ['A','B']
df = pd.DataFrame(data, index_date, columns=columns_list)
print(df)

ValueError: Shape of passed values is (4, 3), indices imply (4, 2)

In [103]:
data = {'연도':[2015,2016,2016,2017,2017], '지사':['서울','서울','부산','서울','부산'],'고객 수':[200,250,150,300,200]}
df = pd.DataFrame(data)
print(df)

     연도  지사  고객 수
0  2015  서울   200
1  2016  서울   250
2  2016  부산   150
3  2017  서울   300
4  2017  부산   200


In [106]:
data1 = {'A':[1,2,3,4,5],'B':[10,20,30,40,50],'C':[100,200,300,400,500]}
df1 = pd.DataFrame(data1)
print(df1)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500


In [107]:
data2 = {'A':[6,7,8],'B':[60,70,80],'C':[600,700,800]}
df2 = pd.DataFrame(data2)
print(df2)

   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800


In [108]:
print(df1+df2)

      A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN


In [124]:
table_data3 = {'봄':[256.5,264.3,215.9,223.2,312.8],
               '여름':[770.6,567.5,599.8,387.1,446.2],
               '가을':[363.5,231.2,293.1,247.7,381.6],
               '겨울':[139.3,59.9,76.9,109.1,108.1]}
columns_list = ['봄','여름','가을','겨울']
index_list = ['2012','2013','2014','2015','2016']

In [126]:
df3 = pd.DataFrame(table_data3, columns=columns_list,index=index_list)
print(df3)

          봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1


In [127]:
print(df3.mean())

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64


In [128]:
print(df3.mean(axis =1))

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64


In [129]:
print(df3.describe())

                봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000


In [133]:
KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

In [135]:
df_KTX = pd.DataFrame(KTX_data, columns=col_list, index= index_list)
print(df_KTX)

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0


In [137]:
print(df_KTX.info())

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 2011 to 2017
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   경부선 KTX  7 non-null      int64  
 1   호남선 KTX  7 non-null      int64  
 2   경전선 KTX  7 non-null      int64  
 3   전라선 KTX  7 non-null      int64  
 4   동해선 KTX  3 non-null      float64
dtypes: float64(1), int64(4)
memory usage: 336.0+ bytes
None


In [138]:
print(df_KTX.tail())

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0


In [139]:
print(df_KTX[1:2])

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN


In [140]:
print(df_KTX[2:5])

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0


In [141]:
print(df_KTX.loc['2011'])

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX     3627.0
전라선 KTX      309.0
동해선 KTX        NaN
Name: 2011, dtype: float64


In [142]:
print(df_KTX.loc['2013':'2016'])

      경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0


In [143]:
print(df_KTX['경부선 KTX'])

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64


In [144]:
print(df_KTX['경부선 KTX']['2012':'2014'])

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64


In [145]:
print(df_KTX.loc['2016']['호남선 KTX'])

10622.0


In [146]:
print(df_KTX['호남선 KTX'][5])

10622


In [147]:
print(df_KTX['호남선 KTX'].loc['2016'])

10622


In [148]:
print(df_KTX.T)

            2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0


In [149]:
print(df_KTX[['동해선 KTX','전라선 KTX', '경전선 KTX', '호남선 KTX', '경부선 KTX']])

      동해선 KTX  전라선 KTX  경전선 KTX  호남선 KTX  경부선 KTX
2011      NaN      309     3627     7313    39060
2012      NaN     1771     4168     6967    39896
2013      NaN     1954     4088     6873    42005
2014      NaN     2244     4424     6626    43621
2015   2395.0     3146     4606     8675    41702
2016   3786.0     3945     4984    10622    41266
2017   6667.0     5766     5570     9228    32427


In [151]:
df1 = pd.DataFrame({'Class1':[95,92,98,100], 'Class2':[91,93,97,99]})
print(df1)

   Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99


In [152]:
df1 = pd.DataFrame({'Class1':[87,89],'Class2':[85,90]})
print(df2)

   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800


In [154]:
print(df1.append(df2,ignore_index=True))

   Class1  Class2    A     B      C
0    87.0    85.0  NaN   NaN    NaN
1    89.0    90.0  NaN   NaN    NaN
2     NaN     NaN  6.0  60.0  600.0
3     NaN     NaN  7.0  70.0  700.0
4     NaN     NaN  8.0  80.0  800.0


In [155]:
df3 = pd.DataFrame({'Class1':[96,83]})
print(df3)

   Class1
0      96
1      83


In [156]:
print(df2.append(df3,ignore_index = True))

     A     B      C  Class1
0  6.0  60.0  600.0     NaN
1  7.0  70.0  700.0     NaN
2  8.0  80.0  800.0     NaN
3  NaN   NaN    NaN    96.0
4  NaN   NaN    NaN    83.0


In [157]:
df4 = pd.DataFrame({'Class3':[93,91,95,98]})
print(df4)

   Class3
0      93
1      91
2      95
3      98


In [158]:
print(df1)

   Class1  Class2
0      87      85
1      89      90


In [159]:
print(df1.join(df4))

   Class1  Class2  Class3
0      87      85      93
1      89      90      91


In [162]:
index_label = ['a','b','c','d']
df1a = pd.DataFrame({'Class1':[95,92,98,100], 'Class2':[91,93,97,99]}, index=index_label)
df4a = pd.DataFrame({'Class3': [93,91,95,98]}, index=index_label)
print(df1a)

   Class1  Class2
a      95      91
b      92      93
c      98      97
d     100      99


In [163]:
df5 = pd.DataFrame({'Class4':[82,92]})
print(df5)

   Class4
0      82
1      92


In [164]:
print(df1)

   Class1  Class2
0      87      85
1      89      90


In [165]:
print(df1.join(df5))
# join할 때 모자란 부분은 Nan으로 채워진다

   Class1  Class2  Class4
0      87      85      82
1      89      90      92


In [166]:
df_A_B = pd.DataFrame({'판매월':['1월','2월','3월','4월'],\
                       '청소기': [100,150, 200,130],\
                       '세탁기':[90,110,140,170]})
print(df_A_B)

  판매월  청소기  세탁기
0  1월  100   90
1  2월  150  110
2  3월  200  140
3  4월  130  170


In [167]:
df_C_D = pd.DataFrame({'판매월':['1월','2월','3월','4월'],\
                       '냉장고': [112,141, 203,134],\
                       '에어컨':[90,110,150,160]})
print(df_C_D)

  판매월  냉장고  에어컨
0  1월  112   90
1  2월  141  110
2  3월  203  150
3  4월  134  160


In [168]:
print(df_A_B.merge(df_C_D))

  판매월  청소기  세탁기  냉장고  에어컨
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  203  150
3  4월  130  170  134  160


In [169]:
df_left = pd.DataFrame({'key': ['A','B','C'], 'left':[1,2,3]})
print(df_left)

  key  left
0   A     1
1   B     2
2   C     3


In [170]:
df_right = pd.DataFrame({'key':['A','B','D'],'right':[4,5,6]})
print(df_right)

  key  right
0   A      4
1   B      5
2   D      6


In [171]:
# 데이터가 상이할 떄 merge 하는 방법
print(df_left.merge(df_right, how='left', on='key'))

  key  left  right
0   A     1    4.0
1   B     2    5.0
2   C     3    NaN


In [172]:
print(df_left.merge(df_right, how='right', on='key'))
# right 기준으로 붙인다

  key  left  right
0   A   1.0      4
1   B   2.0      5
2   D   NaN      6


In [173]:
print(df_left.merge(df_right, how='outer', on='key'))
# 양쪽 기준으로

  key  left  right
0   A   1.0    4.0
1   B   2.0    5.0
2   C   3.0    NaN
3   D   NaN    6.0


In [174]:
data = {'연도': [2015, 2016, 2016, 2017, 2017], 
        '지사': ['서울', '서울', '부산', '서울', '부산'],
        '고객 수': [200, 250, 150, 300, 200]}
df = pd.DataFrame(data, columns=['지사','연도', '고객 수'])
print(df)

   지사    연도  고객 수
0  서울  2015   200
1  서울  2016   250
2  부산  2016   150
3  서울  2017   300
4  부산  2017   200


In [175]:
row = ['대전',2018,500]

In [177]:
df = df.append(pd.Series(row, index=df.columns), ignore_index=True)
print(df)
# Seriess는 새로 생인 놈인데, ~~ 하면 안되서 콜롬으로 붙인다 

   지사    연도  고객 수
0  서울  2015   200
1  서울  2016   250
2  부산  2016   150
3  서울  2017   300
4  부산  2017   200
5  대전  2018   500
